Leader Componente
Computer-Society-Uniandes/webpage_cs pull request #4
Opened 2024-01-05 22:37 UTC by Felipe34515

![image](https://github.com/Computer-Society-Uniandes/webpage_cs/assets/78154196/13509f97-3ad0-4a89-a063-1e6ca6829309)
Closes #2

2024-01-08 20:54 UTC, Crola1702 requested changes
Just some questions before approving

2024-01-08 20:54 UTC, Crola1702 commented on src/components/codeHome.astro
Why adding `codeHome` file for the `Leader` component?

2024-01-08 20:54 UTC, Crola1702 commented on src/pages/LiderDetail.astro
> +        <path d="M8.10059 19.0137C8.10059 19.1113 7.98828 19.1895 7.84668 19.1895C7.68555 19.2041 7.57324 19.126 7.57324 19.0137C7.57324 18.916 7.68555 18.8379 7.82715 18.8379C7.97363 18.8232 8.10059
What are these big numbers in the path?

2024-01-08 20:54 UTC, Crola1702 commented on src/pages/index.astro
Why changing the whole index page for the `Leader` component?

2024-01-08 20:54 UTC, Crola1702 commented on src/pages/ProyectosEnCurso.astro
Why adding current project for in the `Leader` component?

2024-01-08 22:23 UTC, Felipe34515 commented on src/pages/index.astro
There was a problem, apparently, when I made the animation of the Homepage and Project website, it was saved in the Pull request of leader component. I changed the index for the HomePage.

2024-01-08 22:23 UTC, Felipe34515 commented on src/pages/ProyectosEnCurso.astro
There was a problem, apparently, when I made the animation of the Homepage and Project website, it was saved in the Pull request of leader component. I changed the index for the HomePage.

2024-01-17 00:04 UTC, Crola1702 approved these changes
LGTM

2024-01-17 00:04 UTC, Crola1702 commented
After conflicts resolved

2024-01-19 15:32 UTC, mr-sosa commented
Finally, don't forget resolved the merge conflicts. You must leave the index.astro of your branch as it's in the branch develop

2024-01-21 16:52 UTC, merged