animación Homepage V1
Computer-Society-Uniandes/webpage_cs pull request #6
Opened 2024-01-10 21:30 UTC by Felipe34515

Hacer la primera versión de la HomePage con animación en el código

2024-01-17 00:08 UTC, Crola1702 requested changes
Just one minor comment

2024-01-17 00:08 UTC, Crola1702 commented on src/layouts/Layout.astro
> +		<title>Computer Society</title>
I think it's not a good idea to hardcode the title here. Please revert this change and add your title as a prop.

2024-01-17 13:43 UTC, Crola1702 approved these changes
LGTM

2024-01-17 13:43 UTC, Crola1702 commented
After solving conflicts

2024-01-19 15:12 UTC, mr-sosa commented
Finally, don't forget resolved the merge conflicts. You must leave the index.astro of your branch as it's in the branch develop

2024-01-21 16:11 UTC, merged